const CassandraTypes = Object.freeze({
  ASCII: "ascii",
  BIGINT: "bigint",
  BOOLEAN: "boolean",
  DATE: "date",
  DECIMAL: "decimal",
  DOUBLE: "double",
  DURATION: "duration",
  FLOAT: "float",
  INET: "inet",
  INT: "int",
  SMALLINT: "smallint",
  TEXT: "text",
  TIME: "time",
  TIMESTAMP: "timestamp",
  TIMEUUID: "timeuuid",
  TINYINT: "tinyint",
  UUID: "uuid",
  VARCHAR: "varchar",
  VARINT: "varint",
  MAP: "map",
  SET: "set",
  LIST: "list",
  TUPLE: "tuple",
});

export { CassandraTypes };
